---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: roon
  tasks:

    - name: Debug - zone name
      debug:
        msg: "{{ vars }}"

    - name: Create a group
      group:
        name: "{{ service.group }}"
        state: present

    - name: Ensure service has been stopped
      ignore_errors: yes
      systemd:
        name: "{{ service.name }}.service"
        state: stopped
        enabled: false

    - name: Create a user
      user:
        name: "{{ service.user }}"
        comment: Roon Remote User
        groups: "{{ service.groups }}"

    - name: Remove Installation Folder
      tags: sebman
      file:
        dest: "{{ installation.folder }}/"
        state: absent

    - name: Cleanup the APP folder
      delegate_to: localhost
      tags: sebman
      file:
        state: absent
        path: "../app/__pycache__/"

    - name: Transfer the code
      tags: sebman
      copy:
        src: "{{ item.src }}"
        dest: "{{ installation.folder }}/{{ item.dest }}"
        owner: "{{ service.user }}"
        group: "{{ service.group }}"
        mode: "750"
      loop:
        - { src: '../app/', dest: 'app/' }
        - { src: '../roon_remote.py', dest: 'roon_remote.py' }

    - name: Generate template
      template:
        dest: "{{ installation.folder }}/app_info.json"
        src: "app_info.json.j2"
        owner: "{{ service.user }}"
        group: "{{ service.group }}"
        mode: '770'

    - name: PIP install required packages
      pip:
        name: [ 'roonapi', 'evdev' ]
        state: present

    - name: Copy systemd service file
      copy:
        src: "{{ service.name }}.service"
        dest: "/etc/systemd/system/{{ service.name }}.service"

    - name: Enable and start the service
      systemd:
        name: "{{ service.name }}.service"
        daemon_reload: true
        enabled: true
        state: started
